<#
.SYNOPSIS
  Manage multiple GitHub identities on one machine.
.DESCRIPTION
  setup   One-time (re-runnable): writes git config so every repo under a
          profile's root folder uses that profile's name, email, signing key
          and GitHub account. Repos elsewhere use the default profile.
  switch  Changes the active gh CLI account (the only global state).
  status  Shows which identity git and gh will use in the current directory.
.EXAMPLE
  .\ghprofile.ps1 setup
  .\ghprofile.ps1 switch personal
  .\ghprofile.ps1 status
#>
param(
    [Parameter(Mandatory, Position = 0)][ValidateSet('setup', 'switch', 'status')][string]$Command,
    [Parameter(Position = 1)][string]$Name
)
$ErrorActionPreference = 'Stop'

$config = Get-Content (Join-Path $PSScriptRoot 'profiles.json') -Raw | ConvertFrom-Json
$homeFwd = $HOME.Replace('\', '/')
function Expand([string]$p) { ($p -replace '^~(?=/)', $homeFwd).Replace('\', '/') }
function Get-Prof([string]$n) {
    $p = $config.profiles.$n
    if (-not $p) { throw "Unknown profile '$n'. Known: $($config.profiles.PSObject.Properties.Name -join ', ')" }
    if ($p.email -like 'REPLACE-ME*' -or $p.ghUser -eq 'REPLACE-ME') { throw "Fill in profile '$n' in profiles.json first." }
    $p
}
function Get-GhActive { gh auth status --hostname github.com --json hosts --jq '.hosts[][] | select(.active) | .login' 2>$null }

function Set-SigningKey($p) {
    $pub = Expand $p.signingKey
    if (-not (Test-Path $pub)) {
        Write-Host "Generating signing key $pub (set a passphrase when prompted)"
        ssh-keygen -t ed25519 -C $p.email -f ($pub -replace '\.pub$', '')
        if ($LASTEXITCODE) { throw 'ssh-keygen failed' }
    }
    # Signing without ssh-agent loads the private key from the .pub path minus '.pub'.
    $priv = $pub -replace '\.pub$', ''
    if (-not (Test-Path $priv)) { throw "Private key $priv not found. Copy it next to $pub, or delete $pub so setup generates a new pair." }
    # Register the key for local signature verification, if that is configured.
    $signers = git config --global gpg.ssh.allowedsignersfile
    $line = "$($p.email) $((Get-Content $pub -Raw).Trim())"
    if ($signers -and -not ((Test-Path $signers) -and (Select-String -Path $signers -SimpleMatch $line -Quiet))) {
        Add-Content $signers $line
    }
    $pub
}

switch ($Command) {
    'setup' {
        $gitconfig = Join-Path $HOME '.gitconfig'
        $backup = "$gitconfig.bak-$(Get-Date -Format yyyyMMdd-HHmmssfff)"
        Copy-Item $gitconfig $backup
        Write-Host "Backed up $gitconfig -> $backup"

        # Default profile lives in the global config. Set the credential username
        # before any includeIf so that later includes override it (last value wins).
        $d = Get-Prof $config.default
        git config --global user.name $d.name
        git config --global user.email $d.email
        git config --global user.signingkey (Set-SigningKey $d)
        git config --global credential.https://github.com.username $d.ghUser

        foreach ($n in $config.profiles.PSObject.Properties.Name | Where-Object { $_ -ne $config.default }) {
            $p = Get-Prof $n
            if (-not $p.root) { throw "Profile '$n' needs a 'root' folder." }
            $root = (Expand $p.root).TrimEnd('/') + '/'
            New-Item -ItemType Directory -Force $root | Out-Null
            $inc = "$homeFwd/.gitconfig-$n"
            Set-Content $inc @"
# Generated by ghprofile.ps1 from profiles.json - edit that file and re-run setup.
[user]
	name = $($p.name)
	email = $($p.email)
	signingkey = $(Set-SigningKey $p)
[credential "https://github.com"]
	username = $($p.ghUser)
"@
            git config --global "includeIf.gitdir/i:$root.path" $inc
            Write-Host "Profile '$n': repos under $root use $($p.email) / $($p.ghUser)"
        }

        Write-Host "`nOne-time steps per non-default profile (skip any already done):"
        foreach ($n in $config.profiles.PSObject.Properties.Name | Where-Object { $_ -ne $config.default }) {
            $p = $config.profiles.$n
            Write-Host "  gh auth login --hostname github.com --git-protocol https --web --scopes write:ssh_signing_key   # sign in as $($p.ghUser)"
            Write-Host "  gh ssh-key add $(Expand $p.signingKey) --type signing --title `"$env:COMPUTERNAME signing`"   # while $($p.ghUser) is active"
            Write-Host "  .\ghprofile.ps1 switch $($config.default)"
        }
    }
    'switch' {
        if (-not $Name) { throw 'Usage: ghprofile.ps1 switch <profile>' }
        $p = Get-Prof $Name
        gh auth switch --hostname github.com --user $p.ghUser
        if ($LASTEXITCODE) { throw "gh has no login for $($p.ghUser). Run: gh auth login --hostname github.com --git-protocol https --web" }
        & $PSCommandPath status
    }
    'status' {
        $email = git config user.email
        $prof = $config.profiles.PSObject.Properties | Where-Object { $_.Value.email -eq $email } | Select-Object -First 1
        $ghActive = Get-GhActive
        # includeIf gitdir only applies inside a repo; elsewhere git reports the default profile.
        $inRepo = (git rev-parse --is-inside-work-tree 2>$null) -eq 'true'
        Write-Host "Directory      : $(Get-Location)"
        if (-not $inRepo) {
            # The git lines would only show the default profile here, which reads as a wrong switch.
            $rules = @($config.profiles.PSObject.Properties | Where-Object { $_.Value.root } |
                ForEach-Object { "repos under $((Expand $_.Value.root).TrimEnd('/'))/ use '$($_.Name)'" }) + "all other repos use '$($config.default)'"
            Write-Host "git profile    : <none - not inside a git repo>"
            Write-Host "gh CLI as      : $ghActive"
            Write-Host "`nGit picks the identity per repo: $($rules -join '; ')."
            Write-Host 'Run status inside a repo to see the identity it will use there.'
            break
        }
        Write-Host "git profile    : $(if ($prof) { $prof.Name } else { '<none matched>' })"
        Write-Host "git identity   : $(git config user.name) <$email>"
        Write-Host "git signing key: $(git config user.signingkey)"
        Write-Host "git push as    : $(git config --get-urlmatch credential.username https://github.com)"
        Write-Host "gh CLI as      : $ghActive"
        if ($prof -and $ghActive -ne $prof.Value.ghUser) {
            Write-Warning "gh CLI is '$ghActive' but this directory is '$($prof.Name)'. Run: .\ghprofile.ps1 switch $($prof.Name)"
        }
    }
}
